# Generated by Django 4.1.2 on 2022-10-18 16:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(default='Channel Name', max_length=40)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='image/profile/image/%Y/%m/')),
                ('banner', models.ImageField(null=True, upload_to='image/profile/banner/%Y/%m/')),
                ('logo', models.ImageField(null=True, upload_to='image/profile/logo/%Y/%m/')),
                ('is_active', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='image/%Y/%m/%d/')),
                ('file', models.FileField(upload_to='video/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mvk'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_hosting.channel', verbose_name='Канал')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
