# Generated by Django 4.1.2 on 2022-12-11 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video_hosting', '0004_remove_video_views_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.ManyToManyField(through='video_hosting.Views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='views',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='views',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_id', to='video_hosting.video'),
        ),
    ]
