# Generated by Django 4.1.2 on 2022-12-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0007_rename_subscribes_channel_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ManyToManyField(related_name='category', to='video_hosting.category'),
        ),
    ]
