# Generated by Django 4.1.2 on 2022-12-30 14:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video_hosting', '0009_likes_video_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': 'Канал', 'verbose_name_plural': 'Каналы'},
        ),
        migrations.AlterModelOptions(
            name='likes',
            options={'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки'},
        ),
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name': 'Подписчик', 'verbose_name_plural': 'Подписчики'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('-created_at',), 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AlterModelOptions(
            name='views',
            options={'ordering': ('-time',), 'verbose_name': 'Просмотр', 'verbose_name_plural': 'Просмотры'},
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ManyToManyField(related_name='category', to='video_hosting.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='video/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mkv', 'DVR'])], verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d/', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.ManyToManyField(related_name='likes', through='video_hosting.Likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=130, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.ManyToManyField(through='video_hosting.Views', to=settings.AUTH_USER_MODEL, verbose_name='Просмотры'),
        ),
    ]
