# Generated by Django 4.1.2 on 2022-12-30 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelmailinglist',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылка'},
        ),
    ]
